### PR TITLE
Improve `update deployment`

### PR DESCRIPTION
**Pull request by mzxyz**
## Changes:

- Split the update deployment function into 3 individual functions: https://github.com/subquery/network-contracts/pull/284#discussion_r1384343884
- Update all the events names

TODO:

- Update revert error codes
- Update test

### CODE REVIEW

**Comment by ianhe8x** [comment]
@mzxyz We should also emit `ProjectLatestDeploymentUpdated`  when creating projects

**Comment by mzxyz** [comment]
> Member

Is it duplicated with `ProjectCreated` event? And for `ProjectCreated` event, will make `setLatestDeployment` as default

**Comment by mzxyz** [comment]
> @mzxyz We should also emit `ProjectLatestDeploymentUpdated` when creating projects

Is it duplicated with ProjectCreated event? And for ProjectCreated event, will make setLatestDeployment as default

**Comment by ianhe8x** [comment]
Then it's just the tests to be fixed.

**Pull request merged**
